/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package avl;

import Comom.Param;
import Comom.Tree;

/**
 *
 * @author ddung
 */
public class UIAvl extends javax.swing.JFrame {
        private static final long serialVersionUID = 1L;
        private AvlTreeLogic AvlTree;
    /**
     * Creates new form UIAvl
     */
    public UIAvl() {
       
        this.setTitle("Avl Tree");
        this.setSize(Param.WIDTH + 50, Param.HEIGHT);
        AvlTree = new AvlTreeLogic();
        treePanel = new TreePanel();
        initComponents();
        Random.setBackground(Param.COLOR_BUTT_CREATE);
        Add.setBackground(Param.COLOR_ADDED);
        Clear.setBackground(Param.COLOR_BUTT_CLEAR);
        Remove.setBackground(Param.COLOR_BUTT_REMOVE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        InputNumber = new javax.swing.JTextField();
        Random = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        treePanel = new avl.TreePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(203, 188, 172));

        Random.setText("Random");
        Random.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickRandomButton(evt);
            }
        });

        Add.setText("Add");
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickAddButton(evt);
            }
        });

        Search.setText("Search");
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSearchButton(evt);
            }
        });

        Remove.setText("Remove");
        Remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickRemoveButton(evt);
            }
        });

        Clear.setText("Clear");
        Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickClearButton(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InputNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Random, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Random)
                    .addComponent(Add)
                    .addComponent(Search)
                    .addComponent(Remove)
                    .addComponent(Clear))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout treePanelLayout = new javax.swing.GroupLayout(treePanel);
        treePanel.setLayout(treePanelLayout);
        treePanelLayout.setHorizontalGroup(
            treePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        treePanelLayout.setVerticalGroup(
            treePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(treePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(treePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clickRandomButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickRandomButton
        // TODO add your handling code here:
        int val = (int) ((Math.random()*100)+1);
        addNode(val);     
    }//GEN-LAST:event_clickRandomButton

    private void clickAddButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickAddButton
        // TODO add your handling code here:
        int value; 
	try {
	    value = Integer.parseInt(InputNumber.getText());
	} catch (NumberFormatException e) {
	  
            System.out.println("not a number");
	
            return;
        }			
	addNode(value);

    }//GEN-LAST:event_clickAddButton

    private void clickSearchButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSearchButton
        // TODO add your handling code here:
        int value;
				
	try {
	value = Integer.parseInt(InputNumber.getText());
	} catch (NumberFormatException e) {
	System.out.println("not a number");				
	return;
	}
				
	Tree result = AvlTree.searchNode(value);
	if (result == null) {
            System.out.println("Khong tim thay so");	
	} else {
            System.out.println(result.getValue());
	}
	treePanel.repaint();
    }//GEN-LAST:event_clickSearchButton

    private void clickRemoveButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickRemoveButton
        // TODO add your handling code here:
        int value;
				
	try {
		value = Integer.parseInt(InputNumber.getText());
	} catch (NumberFormatException e) {
	System.out.println("not a number");
            return;
	}			
	AvlTreeLogic.setAdded(-1000);
        AvlTreeLogic.setDegenerated(-1000);
        AvlTreeLogic.setRemoved(value);
	Tree forRemove = AvlTree.searchNode(value);
	if (forRemove == null) {
            
		return;
	}
				
	AvlTreeLogic.setRemoved(value);
	treePanel.repaint();
	new java.util.Timer().schedule( 
	new java.util.TimerTask() {
	@Override
	 public void run() {
		AvlTree.removeNode(forRemove);
			treePanel.repaint();
		}
        }, 
        2000 
	);
    }//GEN-LAST:event_clickRemoveButton

    private void clickClearButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickClearButton
        // TODO add your handling code here:
        AvlTree.clearTree();
        treePanel.repaint();
        return;
    }//GEN-LAST:event_clickClearButton

    private void addNode(int value){
                Tree localTree = AvlTree.addNode(value);
                if(localTree!=null){
                    Tree degTree = AvlTree.chekDeg(localTree);
                    setXY(localTree);
                    treePanel.startAction();
                    if (degTree != null){
			AvlTreeLogic.setDegenerated(degTree.getValue());
			new java.util.Timer().schedule( 
				new java.util.TimerTask() {
					@Override
					public void run() {
						AvlTreeLogic.setDegenerated(-1000);
						AvlTree.typeOfRotation(degTree);
						treePanel.startAction();
					}
				}, 
				2000 
			);		
                    }   
            }
    }
    public void setXY(Tree localTree){
           Tree parent = localTree.getParent();
           if(parent == null){
               localTree.setX(Param.WIDTH/2);
               localTree.setY(Param.TOP_MARGIN);
           }else{
               if(parent.getParent() == null){
                    if(localTree.getValue() < parent.getValue()){
                        localTree.setX(Param.WIDTH/4);
                        localTree.setY(Param.NODE_MARGIN + parent.getY());
                    }else{
                        localTree.setX(Param.WIDTH - Param.WIDTH/4);
                        localTree.setY(Param.NODE_MARGIN + parent.getY());
                    }
               } else {
                   
                   if (localTree.getValue() < parent.getValue()){
                            localTree.setX(parent.getX() - Math.abs(parent.getX() - parent.getParent().getX())/2);
                            localTree.setY(Param.NODE_MARGIN + parent.getY());
			} else {
                            localTree.setX(parent.getX() + Math.abs(parent.getX() - parent.getParent().getX())/2);
                            localTree.setY(Param.NODE_MARGIN + parent.getY());
			}
               }
           }
    }
    
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Clear;
    private javax.swing.JTextField InputNumber;
    private javax.swing.JButton Random;
    private javax.swing.JButton Remove;
    private javax.swing.JButton Search;
    private javax.swing.JPanel jPanel2;
    private avl.TreePanel treePanel;
    // End of variables declaration//GEN-END:variables
}
